networks:
  go:
    driver: bridge

volumes:
  goroot:
  gocache:
  mariadbdata:
  # pgdata:

services:
  app:
    container_name: app
    image: golang:1.22-alpine
    volumes:
      - .:/app
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      go:
        aliases:
          - app
    depends_on:
      - mysql_db

    mysql_db:
      container_name: db
      image: mariadb:lts
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: absensi_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: password
      volumes:
        - mariadbdata:/var/lib/mysql
      ports:
        - "3306:3306"
      networks:
        net:
          aliases:
            - mysql
    # pgsql_db:
    #   image: postgres:16-alpine
    #   restart: always
    #   shm_size: 128mb
    #   environment:
    #     POSTGRES_PASSWORD: password
    #     POSTGRES_DB: auth_db
    #   volumes:
    #     - pgdata:/var/lib/postgresql/data
    #   ports:
    #     - 5432:5432
    #   networks:
    #     go:
    #       aliases:
    #         - auth_db

    swagger:
      image: swaggerapi/swagger-ui:latest
      environment:
        - URL=/docs/swagger.yaml
      volumes:
        - ./docs:/usr/share/nginx/html/docs
      ports:
        - 8084:8080