networks:
  go:
    driver: bridge

volumes:
  goroot:
  gocache:
  pgdata:
  redis:
  minio:

services:
  app:
    container_name: app
    image: golang:1.22-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      go:
        aliases:
          - app
    command:
      - tail
      - -f
      - /etc/hosts
    # depends_on:
    #   - pgsql_db

  pgsql_db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgsql_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      go:
        aliases:
          - pgsql_db

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

  # swagger:
  #   image: swaggerapi/swagger-ui:latest
  #   environment:
  #     - URL=/docs/swagger.yaml
  #   volumes:
  #     - ./docs:/usr/share/nginx/html/docs
  #   ports:
  #     - 8084:8080

  # minio:
  #   image: quay.io/minio/minio
  #   ports:
  #     - '9000:9000'
  #     - '9001:9001'
  #   networks:
  #     go:
  #       aliases:
  #         - minio
  #   volumes:
  #     - 'minio:/data'
  #   environment:
  #     - MINIO_ROOT_USER=miniouser
  #     - MINIO_ROOT_PASSWORD=password
  #     - MINIO_DEFAULT_BUCKETS=bucketname